In [31]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
from sklearn import metrics


In [32]:
df=pd.read_csv(r'C:\Users\Sony\Desktop\python\covid19\another dataset\covid.csv')
df.head()

id  sex  patient_type  entry_date date_symptoms   date_died  intubed  \
0  16169f    2             1    4/5/2020      2/5/2020  9999-99-99       97   
1  1009bf    2             1  19-03-2020    17-03-2020  9999-99-99       97   
2  167386    1             2    6/4/2020      1/4/2020  9999-99-99        2   
3  0b5948    2             2  17-04-2020     10/4/2020  9999-99-99        2   
4  0d01b5    1             2  13-04-2020    13-04-2020  22-04-2020        2   

   pneumonia  age  pregnancy ...   inmsupr  hypertension  other_disease  \
0          2   27         97 ...         2             2              2   
1          2   24         97 ...         2             2              2   
2          2   54          2 ...         2             2              2   
3          1   30         97 ...         2             2              2   
4          2   60          2 ...         2             1              2   

   cardiovascular  obesity  renal_chronic  tobacco  contact_other_covid  \
0               2        2              2        2                    2   
1               2        2              2        2                   99   
2               2        1              2        2                   99   
3               2        2              2        2                   99   
4               1        2              2        2                   99   

   covid_res  icu  
0          1   97  
1          1   97  
2          1    2  
3          1    2  
4          1    2  

[5 rows x 23 columns]

In [33]:
df=df.drop(['id','entry_date','date_symptoms','date_died'],axis=1)

In [34]:
df.rename(columns={'covid_res':'Test_result'},inplace=True)

In [36]:
df['sex']=df['sex'].replace({1:'Female',2:'Male'})
df['patient_type']=df['patient_type'].replace({1:'Outpatient',2:'Inpatient'})
df['Test_result']=df['Test_result'].replace({1:'Positive',2:'Negative',3:'Results Awaited'})

df.iloc[:,6:]=df.iloc[:,6:].replace([97,98,99],np.nan)
df.iloc[:,6:]=df.iloc[:,6:].replace(1,'Yes')
df.iloc[:,6:]=df.iloc[:,6:].replace(2,'No')

In [37]:
# Get names of indexes for which column Stock has value No
indexNames = df[ df['Test_result'] == 'Results Awaited' ].index
# Delete these row indexes from dataFrame
df.drop(indexNames , inplace=True)
df.head()

sex patient_type  intubed  pneumonia  age  pregnancy diabetes copd  \
0    Male   Outpatient       97          2   27         97       No   No   
1    Male   Outpatient       97          2   24         97       No   No   
2  Female    Inpatient        2          2   54          2       No   No   
3    Male    Inpatient        2          1   30         97       No   No   
4  Female    Inpatient        2          2   60          2      Yes   No   

  asthma inmsupr hypertension other_disease cardiovascular obesity  \
0     No      No           No            No             No      No   
1     No      No           No            No             No      No   
2     No      No           No            No             No     Yes   
3     No      No           No            No             No      No   
4     No      No          Yes            No            Yes      No   

  renal_chronic tobacco contact_other_covid Test_result  icu  
0            No      No                  No    Positive  NaN  
1            No      No                 NaN    Positive  NaN  
2            No      No                 NaN    Positive   No  
3            No      No                 NaN    Positive   No  
4            No      No                 NaN    Positive   No

In [38]:
cat_features=df.select_dtypes(include='object').columns.tolist()
print("Categorical Features:",cat_features)
num_features=df.select_dtypes(exclude='object').columns.tolist()
print("Numerical Features:",num_features)

Categorical Features: ['sex', 'patient_type', 'diabetes', 'copd', 'asthma', 'inmsupr', 'hypertension', 'other_disease', 'cardiovascular', 'obesity', 'renal_chronic', 'tobacco', 'contact_other_covid', 'Test_result', 'icu']
Numerical Features: ['intubed', 'pneumonia', 'age', 'pregnancy']


In [39]:
df['sex']=df['sex'].fillna(df['sex'].mode()[0])
df['sex'].isnull().sum()

0

In [40]:
df['patient_type']=df['patient_type'].fillna(df['patient_type'].mode()[0])
df['patient_type'].isnull().sum()

0

In [41]:
df['intubed']=df['intubed'].fillna(df['intubed'].mode()[0])
df['intubed'].isnull().sum()

0

In [42]:
df['pneumonia']=df['pneumonia'].fillna(df['pneumonia'].mode()[0])
df['pneumonia'].isnull().sum()

0

In [43]:
df['diabetes']=df['diabetes'].fillna(df['diabetes'].mode()[0])
df['diabetes'].isnull().sum()

0

In [44]:
df['pregnancy']=df['pregnancy'].fillna(df['pregnancy'].mode()[0])
df['pregnancy'].isnull().sum()

0

In [45]:
df['copd']=df['copd'].fillna(df['copd'].mode()[0])
df['copd'].isnull().sum()

0

In [46]:
df['asthma']=df['asthma'].fillna(df['asthma'].mode()[0])
df['asthma'].isnull().sum()

0

In [47]:
df['inmsupr']=df['inmsupr'].fillna(df['inmsupr'].mode()[0])
df['inmsupr'].isnull().sum()

0

In [48]:
df['hypertension']=df['hypertension'].fillna(df['hypertension'].mode()[0])
df['hypertension'].isnull().sum()

0

In [49]:
df['tobacco']=df['tobacco'].fillna(df['tobacco'].mode()[0])
df['tobacco'].isnull().sum()

0

In [50]:
df['renal_chronic']=df['renal_chronic'].fillna(df['renal_chronic'].mode()[0])
df['renal_chronic'].isnull().sum()

0

In [51]:
df['obesity']=df['obesity'].fillna(df['obesity'].mode()[0])
df['obesity'].isnull().sum()

0

In [52]:
df['cardiovascular']=df['cardiovascular'].fillna(df['cardiovascular'].mode()[0])
df['cardiovascular'].isnull().sum()

0

In [53]:
df['contact_other_covid']=df['contact_other_covid'].fillna(df['contact_other_covid'].mode()[0])
df['contact_other_covid'].isnull().sum()

0

In [54]:
df['other_disease']=df['other_disease'].fillna(df['other_disease'].mode()[0])
df['other_disease'].isnull().sum()

0

In [55]:
df['icu']=df['icu'].fillna(df['icu'].mode()[0])
df['icu'].isnull().sum()

0

In [56]:
df.isnull().sum()

sex                    0
patient_type           0
intubed                0
pneumonia              0
age                    0
pregnancy              0
diabetes               0
copd                   0
asthma                 0
inmsupr                0
hypertension           0
other_disease          0
cardiovascular         0
obesity                0
renal_chronic          0
tobacco                0
contact_other_covid    0
Test_result            0
icu                    0
dtype: int64

In [57]:
from sklearn.preprocessing import StandardScaler,LabelEncoder
cat_features=df.select_dtypes(include='object').columns.tolist()
le=LabelEncoder()
for col in cat_features:
    df[col]=le.fit_transform(df[col])
    

In [58]:
from sklearn.model_selection import train_test_split
x = df.drop('Test_result', axis = 1)
y = df.Test_result
from sklearn.preprocessing import RobustScaler
x= RobustScaler().fit_transform(x)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.3)

In [60]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics


Ada_model=AdaBoostClassifier(DecisionTreeClassifier(max_depth=1),n_estimators=500,learning_rate=0.1)
Ada_model.fit(x_train,y_train)
ada_pred=Ada_model.predict(x_test)
ada_accuracy = metrics.accuracy_score(y_test, ada_pred)
print("ada_accuracy",ada_accuracy)

ada_precision=metrics.precision_score(y_test, ada_pred,pos_label=0)
print("ada_precision",ada_precision)

ada_recall=metrics.recall_score(y_test, ada_pred,pos_label=0)
print("ada_recall",ada_recall)

ada_f1_score= metrics.f1_score(y_test, ada_pred,pos_label=0)
print("ada_f1_score",ada_f1_score)

print(confusion_matrix(y_test,ada_pred))
print(classification_report(y_test,ada_pred))

ada_accuracy 0.6343557381860875
ada_precision 0.6260986798333158
ada_recall 0.8552636299494146
ada_f1_score 0.7229553851674761
[[71518 12103]
 [42710 23577]]
             precision    recall  f1-score   support

          0       0.63      0.86      0.72     83621
          1       0.66      0.36      0.46     66287

avg / total       0.64      0.63      0.61    149908



In [59]:
from sklearn.ensemble import GradientBoostingClassifier

Grad_boost = GradientBoostingClassifier()
Grad_boost.fit(x_train, y_train)
Grad_boost_pred = Grad_boost.predict(x_test)
Grad_boost_accuracy = metrics.accuracy_score(y_test, Grad_boost_pred)
print("Grad_boost_accuracy",Grad_boost_accuracy)

Grad_boost_precision=metrics.precision_score(y_test, Grad_boost_pred,pos_label=0)
print("Grad_boost_precision",Grad_boost_precision)

Grad_boost_recall=metrics.recall_score(y_test, Grad_boost_pred,pos_label=0)
print("Grad_boost_recall",Grad_boost_recall)

Grad_boost_f1_score= metrics.f1_score(y_test, Grad_boost_pred,pos_label=0)
print("Grad_boost_f1_score",Grad_boost_f1_score)

print(confusion_matrix(y_test,Grad_boost_pred))
print(classification_report(y_test,Grad_boost_pred))

Grad_boost_accuracy 0.6363169410571817
Grad_boost_precision 0.625489418217569
Grad_boost_recall 0.867341935638177
Grad_boost_f1_score 0.7268245020668922
[[72528 11093]
 [43426 22861]]
             precision    recall  f1-score   support

          0       0.63      0.87      0.73     83621
          1       0.67      0.34      0.46     66287

avg / total       0.65      0.64      0.61    149908



# Logistic regression without CV

In [61]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression(class_weight='balanced')
log.fit(x_train, y_train)
log_pred = log.predict(x_test)
log_accuracy = metrics.accuracy_score(y_test, log_pred)
print("log_accuracy",log_accuracy)

log_precision=metrics.precision_score(y_test, log_pred,pos_label=0)
print("log_precision",log_precision)

log_recall=metrics.recall_score(y_test, log_pred,pos_label=0)
print("log_recall",log_recall)

log_f1_score= metrics.f1_score(y_test, log_pred,pos_label=0)
print("log_f1_score",log_f1_score)

print(confusion_matrix(y_test,log_pred))
print(classification_report(y_test,log_pred))

log_accuracy 0.6202404141206607
log_precision 0.6417525225703664
log_recall 0.7225577307135768
log_f1_score 0.6797621659325761
[[60421 23200]
 [33729 32558]]
             precision    recall  f1-score   support

          0       0.64      0.72      0.68     83621
          1       0.58      0.49      0.53     66287

avg / total       0.62      0.62      0.62    149908



# Logistic regression with CV

In [63]:
from sklearn.model_selection import cross_val_score
log_cross_val = cross_val_score(log, x, y, cv=10, scoring='accuracy')
log_cv_accuracy = log_cross_val.mean()
print("log_cv_accuracy",log_cv_accuracy)

log_cross_val_pre = cross_val_score(log, x, y, cv=10, scoring='precision_macro')
log_cv_precision = log_cross_val_pre.mean()
print("log_cv_precision",log_cv_precision)

log_cross_val_re = cross_val_score(log, x, y, cv=10, scoring='recall_macro')
log_cv_recall = log_cross_val_re.mean()
print("log_cv_recall",log_cv_recall)

log_cross_val_f1 = cross_val_score(log, x, y, cv=10, scoring='f1_macro')
log_cv_f1_score = log_cross_val_f1.mean()
print("log_cv_f1_score",log_cv_f1_score)

log_cv_accuracy 0.6188171970889943
log_cv_precision 0.6111488639167997
log_cv_recall 0.6052662115249381
log_cv_f1_score 0.6050325901188338


# Multilayer Perceptron

In [64]:
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(max_iter=200,activation='logistic')
MLP.fit(x_train, y_train)
MLP_pred = MLP.predict(x_test)
MLP_accuracy = metrics.accuracy_score(y_test, MLP_pred)
print("MLP_accuracy",MLP_accuracy)

MLP_precision=metrics.precision_score(y_test, MLP_pred,pos_label=0)
print("MLP_precision",MLP_precision)

MLP_recall=metrics.recall_score(y_test, MLP_pred,pos_label=0)
print("MLP_recall",MLP_recall)

MLP_f1_score= metrics.f1_score(y_test, MLP_pred,pos_label=0)
print("MLP_f1_score",MLP_f1_score)

print(confusion_matrix(y_test,MLP_pred))
print(classification_report(y_test,MLP_pred))

MLP_accuracy 0.6366704912346239
MLP_precision 0.6245163274196441
MLP_recall 0.87434974468136
MLP_f1_score 0.7286117173408273
[[73114 10507]
 [43959 22328]]
             precision    recall  f1-score   support

          0       0.62      0.87      0.73     83621
          1       0.68      0.34      0.45     66287

avg / total       0.65      0.64      0.61    149908



# Multilayer Perceptron with Cross Validation

In [65]:
MLP_cross_val = cross_val_score(MLP, x, y, cv=10, scoring='accuracy')
MLP_cv_accuracy = MLP_cross_val.mean()
print("MLP_cv_accuracy",MLP_cv_accuracy)

MLP_cross_val_pre = cross_val_score(MLP, x, y, cv=10, scoring='precision_macro')
MLP_cv_precision = MLP_cross_val_pre.mean()
print("MLP_cv_precision",MLP_cv_precision)

MLP_cross_val_re = cross_val_score(MLP, x, y, cv=10, scoring='recall_macro')
MLP_cv_recall = MLP_cross_val_re.mean()
print("MLP_cv_recall",MLP_cv_recall)

MLP_cross_val_f1 = cross_val_score(MLP, x, y, cv=10, scoring='f1_macro')
MLP_cv_f1_score = MLP_cross_val_f1.mean()
print("MLP_cv_f1_score",MLP_cv_f1_score)

MLP_cv_accuracy 0.6352553242130312
MLP_cv_precision 0.6471512625194834
MLP_cv_recall 0.6061434445793655
MLP_cv_f1_score 0.591509241572409


In [66]:
MLP_cross_val = cross_val_score(MLP, x, y, cv=10, scoring='accuracy')
MLP_cv_accuracy = MLP_cross_val.mean()
print("MLP_cv_accuracy",MLP_cv_accuracy)

MLP_cross_val_pre = cross_val_score(MLP, x, y, cv=10, scoring='precision_macro')
MLP_cv_precision = MLP_cross_val_pre.mean()
print("MLP_cv_precision",MLP_cv_precision)

MLP_cross_val_re = cross_val_score(MLP, x, y, cv=10, scoring='recall_macro')
MLP_cv_recall = MLP_cross_val_re.mean()
print("MLP_cv_recall",MLP_cv_recall)

MLP_cross_val_f1 = cross_val_score(MLP, x, y, cv=10, scoring='f1_macro')
MLP_cv_f1_score = MLP_cross_val_f1.mean()
print("MLP_cv_f1_score",MLP_cv_f1_score)

MLP_cv_accuracy 0.6353653922151061
MLP_cv_precision 0.6459656321908167
MLP_cv_recall 0.6057919943261352
MLP_cv_f1_score 0.5911770879053253
